version: '3'
services:
  frontend:
    build: .
    ports:
      - "8502:8501"
    environment:
      - API_URL=${BASE_URL}
    volumes:
      - .:/app
    networks:
      - app-network
    restart: unless-stopped
    

  cloudflared:
    image: cloudflare/cloudflared:latest
    command: tunnel --no-autoupdate run --token ${CLOUDFLARED_TUNNEL_TOKEN}
    networks:
      - app-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "cloudflared", "tunnel", "info"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

networks:
  app-network:
    driver: bridge
