version: '3'
services:
  frontend:
    build: .
    ports:
      - "8502:8501"
    environment:
      - API_URL=${BASE_URL}
    volumes:
      - .:/app
    networks:
      - app-network
    restart: unless-stopped
    

  cloudflared:
    image: cloudflare/cloudflared:latest
    command: tunnel --no-autoupdate --protocol http2 run --token ${CLOUDFLARED_TUNNEL_TOKEN}
    networks:
      - app-network
    restart: unless-stopped
networks:
  app-network:
    driver: bridge
